### ISSUE TITLE
Proposal: Add a "script" addon

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kurl#142]
the script add on would just run the script, on the server.

for example:

```
apiVersion: "kurl.sh/v1beta1"
kind: "Installer"
metadata: 
  name: ""
spec: 
  kubernetes: 
    version: "latest"
  script: |
    #! /bin/bash
    ...
    ...
```

The script should be saved to a tmp file, named with the hash of the contents, made executable and then executed.
