### ISSUE TITLE
Airgap bundles using "latest" aren't rebuilt

### ISSUE THREAD

**Issue by areed** [replicatedhq/kurl#26]
If you create an installer that is a mix of fixed versions and `latest` then when a new version is released for the component pinned to `latest`, the airgap bundle is not re-generated.

For example, if you POST this yaml when Contour latest is `0.14.0` you'd get back the install URL https://kurl.sh/68970f9 and the airgap bundle would be available at https://kurl.sh/bundle/68970f9.tar.gz.

```
apiVersion: kurl.sh/v1beta1
spec:
  kubernetes:
    version: "1.15.3"
  weave:
    version: "2.5.2"
  contour:
    version: "latest"
```

Then if Contour latest were updated to `0.14.1` the online install URL would correctly install that version but the airgap bundle would continue to install `0.14.0`.
