### ISSUE TITLE
kURL fails with kotsadm

### ISSUE THREAD

**Issue by mytototo** [replicatedhq/kURL#302]
Hi,

I use Vagrant to setup a Ubuntu 18.04 VM. It meets all requirements as defined in the docs: https://kurl.sh/docs/install-with-kurl/system-requirements

When installing without the `kotsadm` addon everything works perfectly.
However, when installing with `kotsadm` the installation fails.

Here is the error:

```bash
[...]
    default: ⚙  Addon kotsadm 1.13.6
    default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    default:                                  
    default: Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -
    default: -:--:-- --:--:--    
    default:  0
    default: curl: (6) Could not resolve host: kotsadm
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The `kURL` config:
```yml
apiVersion: "https://kurl.sh/v1beta1"
kind: "Installer"

metadata: 
  name: ""

spec: 
  kubernetes: 
    version: "1.16.4"
  docker: 
    version: "18.09.8"
  prometheus: 
    version: "0.33.0"
  registry: 
    version: "2.7.1"
  kotsadm: 
    version: "1.13.6"
```

The `Vagrantfile` I use:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "app"
    vb.memory = 8192
    vb.cpus = 4
    vb.gui = false
  end

  config.vm.network "forwarded_port", guest: 6443, host: 6443, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 6783, host: 6783, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 6783, host: 6783, protocol: "udp"
  config.vm.network "forwarded_port", guest: 6784, host: 6784, protocol: "udp"

  config.vm.network "forwarded_port", guest: 5000, host: 5000, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 8800, host: 8800, protocol: "tcp"

end
```

Any idea why?

Thank you for your time.
