### ISSUE TITLE
There should be a prometheus addon

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kurl#31]
We should start with support for the newest version (2.12.0 at this time)

The addon should conform to the standard kurl.sh add-ons and require no additional configuration for a basic prom install

The default “latest” kurl.sh should be updated to include prom

There should be a subfield for grafana version

This should install the default, usable kubernetes monitoring dashboards

```
apiVersion: kurl.sh/v1beta1
kind: Installer
metadata:
  name: ""
spec:
  kubernetes:
    version: "latest"
  prometheus:
    version: "latest"
    grafana:
      version: "latest"   
```
