### ISSUE TITLE
Error to install containerId `'./addons/containerd/1.6.9/assets/runc': No such file or directory`

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/kURL#3683]
By testing kURL master branch against a test server (codeserver/GCP) the following error was faced:

> Will not install host packages containerd.io, no packages found.
> chmod: cannot access './addons/containerd/1.6.9/assets/runc': No such file or directory
> An error occurred on line 41
  
**Following the configuration used:**

k8s version: 1.25.3
docker version: 20.10.17
ubuntu version: 22.04

```
make build/packages/kubernetes/1.25.3/ubuntu-22.04
make build/packages/kubernetes/1.25.3/images
make build/packages/docker/20.10.17/ubuntu-22.04
```

```
KURL_URL=
DIST_URL=
FALLBACK_URL=
INSTALLER_ID=
REPLICATED_APP_URL=https://replicated.app
KURL_UTIL_IMAGE=replicated/kurl-util:alpha
KURL_BIN_UTILS_FILE=
INSTALLER_YAML="apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: latest
spec:
  kubernetes:
    version: 1.25.3
  weave:
    version: 2.8.1
  contour:
    version: 1.23.0
  prometheus:
    version: 0.46.0
  registry:
    version: 2.8.1
  containerd:
    version: 1.6.9
  ekco:
    version: 0.24.1
  minio:
    version: 2022-10-20T00-55-09Z

  # OpenEBS is the default PV provisioner, and
  # will work for single node clusters, or for
  # applications that handle data replication
  # between nodes themselves (MongoDB, Cassandra,
  # etc). If your requirements are different than
  # this, see
  # https://kurl.sh/docs/create-installer/choosing-a-pv-provisioner
  #
  openebs:
    version: 3.3.0
    isLocalPVEnabled: true
    localPVStorageClassName: default"
```  

Following the output from the script:

```sh
$ sudo bash ./install.sh
SELinux is not installed: no configuration will be applied
The installer will use network interface 'ens4' (with IP address '10.154.0.7')
⚙  Running host preflights
[TCP Port Status] Running collector...
[CPU Info] Running collector...
[Amount of Memory] Running collector...
[Block Devices] Running collector...
[Host OS Info] Running collector...
[Ephemeral Disk Usage /var/lib/kubelet] Running collector...
[Kubernetes API TCP Port Status] Running collector...
[ETCD Client API TCP Port Status] Running collector...
[ETCD Server API TCP Port Status] Running collector...
[ETCD Health Server TCP Port Status] Running collector...
[Kubelet Health Server TCP Port Status] Running collector...
[Kubelet API TCP Port Status] Running collector...
[Kube Controller Manager Health Server TCP Port Status] Running collector...
[Kube Scheduler Health Server TCP Port Status] Running collector...
[Filesystem Latency Two Minute Benchmark] Running collector...
[Host OS Info] Running collector...
[Weave Network Policy Controller Metrics Server TCP Port Status] Running collector...
[Weave Net Metrics Server TCP Port Status] Running collector...
[Weave Net Control TCP Port Status] Running collector...
[Node Exporter Metrics Server TCP Port Status] Running collector...
[Host OS Info] Running collector...
[PASS] Number of CPUs: This server has at least 4 CPU cores
[PASS] Amount of Memory: The system has at least 8G of memory
[PASS] Ephemeral Disk Usage /var/lib/kubelet: The disk containing directory /var/lib/kubelet has at least 30Gi of total space, has at least 10Gi of disk space available, and is less than 60% full
[WARN] Kubernetes API TCP Port Status: Another process was already listening on port 6443.
[PASS] ETCD Client API TCP Port Status: Port 2379 is open
[PASS] ETCD Server API TCP Port Status: Port 2380 is open
[PASS] ETCD Health Server TCP Port Status: Port 2381 is available
[WARN] Kubelet Health Server TCP Port Status: Another process was already listening on port 10248.
[WARN] Kubelet API TCP Port Status: Another process was already listening on port 10250.
[WARN] Kube Controller Manager Health Server TCP Port Status: Another process was already listening on port 10257.
[WARN] Kube Scheduler Health Server TCP Port Status: Another process was already listening on port 10259.
[PASS] Filesystem Performance: Write latency is ok (p99 target < 10ms, actual: 2.616846ms)
[PASS] NTP Status: System clock is synchronized
[PASS] NTP Status: Timezone is set to UTC
[PASS] Host OS Info: containerd addon supports ubuntu 18.04
[PASS] Weave Network Policy Controller Metrics Server TCP Port Status: Port 6781 is available
[PASS] Weave Net Metrics Server TCP Port Status: Port 6782 is available
[PASS] Weave Net Control TCP Port Status: Port 6783 is open
[PASS] Node Exporter Metrics Server TCP Port Status: Port 9100 is available
[PASS] Host OS Info: containerd addon supports ubuntu 18.04
Host preflights have warnings
Found pod network: 10.32.0.0/20
Found service network: 10.96.0.0/22
⚙  Addon containerd 1.6.9
⚙  Installing host packages containerd.io
Will not install host packages containerd.io, no packages found.
chmod: cannot access './addons/containerd/1.6.9/assets/runc': No such file or directory
An error occurred on line 41
```
