### ISSUE TITLE
Latest script is returning weave addon version: 2.6.5-20221025 when the latest version is 2.8.1-x

### ISSUE THREAD

**Issue by camilamacedo86** [replicatedhq/kURL#3705]
See: 

```
apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: latest
spec:
  kubernetes:
    version: 1.25.3
  weave:
    version: 2.6.5-20221025
  openebs:
    version: 3.3.0
    isLocalPVEnabled: true
    localPVStorageClassName: default
  minio:
    version: 2022-10-20T00-55-09Z
  contour:
    version: 1.23.0
  registry:
    version: 2.8.1
  prometheus:
    version: 0.60.1-41.7.3
  ekco:
    version: 0.25.0
  kurl:
    installerVersion: v2022.11.10-1
    additionalNoProxyAddresses: []
  containerd:
    version: 1.6.9
```
