### ISSUE TITLE
Upgrade with ekco addon errors

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kURL#425]
I did an install with
```
apiversion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: ""
spec:
  contour:
    version: latest
  docker:
    version: latest
  ekco:
    version: latest
  kotsadm:
    version: latest
  kubernetes:
    version: latest
  prometheus:
    version: latest
  registry:
    version: latest
  rook:
    version: latest
  velero:
    version: latest
  weave:
    version: latest
```
It seemed to go fine. The eck-operator is running, the ekco-reboot service exists.

However I just did an upgrade today and at the end got
```
The Installer "myapp-unstable" is invalid:
* spec.ekco.minReadyMasterNodeCount: Required value
* spec.ekco.minReadyWorkerNodeCount: Required value
* spec.ekco.nodeUnreachableToleration: Required value
* spec.ekco.rookShouldUseAllNodes: Required value
* spec.ekco.shouldDisableRebootServices: Required value
```

Everything seems to still be setup correctly. But it looks like some attempt to re-apply the Installer resource errored, probably because it doesn't match what's outlined in https://github.com/replicatedhq/kURL/blob/master/kurlkinds/config/crds/v1beta1/cluster.kurl.sh_installers.yaml.
