### ISSUE TITLE
Long image name/tags break airgap registry with ceph rgw block storage

### ISSUE THREAD

**Issue by emosbaugh** [replicatedhq/kURL#480]
The following yaml with a long image name will take down the kurl docker registry. I believe this is because osd_max_object_name_len is set to 256 although it looks like its set to 2048.

osd logs

```
2020-05-26 18:09:58.275 7fd585aa7700  4 osd.0 pg_epoch: 39 pg[7.3c( v 34'50 (0'0,34'50] local-lis/les=36/37 n=4 ec=26/26 lis/c 36/36 les/c/f 37/37/0 36/36/36) [0] r=0 lpr=36 crt=34'50 lcod 0'0 mlcod 0'0 active+clean] do_op name is longer than 256 bytes
```

```
[root@rook-ceph-operator-6fbfdccc57-9qw26 /]# ceph config get osd.0 osd_max_object_name_len
2048
```

registry service

```
$ curl -ik https://10.96.3.66/v2/
HTTP/2 503
content-type: application/json; charset=utf-8
content-length: 125
date: Wed, 27 May 2020 03:44:09 GMT

{"errors":[{"code":"UNAVAILABLE","message":"service unavailable","detail":"health check failed: please see /debug/health"}]}
```

rook-ceph-rgw-rook-ceph-store-a logs:

```
debug 2020-05-27 03:42:27.403 7f78d0a7a700  0 WARNING: set_req_state_err err_no=36 resorting to 500
```

bad yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longimagename
  labels:
    app: longimagename
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longimagename
  template:
    metadata:
      labels:
        app: longimagename
    spec:
      containers:
        - name: longimagename
          image: emosbaugh/kafka-prometheus-jmx-exporter:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e7894
```
