### ISSUE TITLE
In an environment behind a proxy kurl.sh installer does not configure docker to use proxy

### ISSUE THREAD

**Issue by divolgin** [replicatedhq/kURL#623]
### Set up the environment
```
export HTTP_PROXY=...
```
edit ~/.curlrc
```
proxy = ...
```
### Install
```
curl https://kurl.sh/latest | sudo bash
```

### Create a pod
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx
EOF
```

The pod will fail to start
```
$ kubectl get pods
NAME            READY   STATUS          RESTARTS   AGE
test-pod        0/1     ErrImagePull    0          74s
```

After configuring docker with proxy and restarting the service, the image is pulled successfully and the pod is started.
