### ISSUE TITLE
Failure when running "ekco-purge-node --help"

### ISSUE THREAD

**Issue by yasserg** [replicatedhq/kURL#901]
```
ekco-purge-node --help
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "95c0981dec8d1d66ae48406ab9f2efdea91ae34e85ea3bce8d8e9678a1dc10f1": OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "purge-node": executable file not found in $PATH: unknown
```

Environment:

```
kubernetes:
    version: 1.19.3
  weave:
    version: 2.6.5
  rook:
    version: 1.4.3
    isBlockStorageEnabled: true
    blockDeviceFilter: sdb1|nvme1n1
  registry:
    version: 2.7.1
  kotsadm:
    version: 1.21.2
    applicationSlug: forward-cluster/beta
  ekco:
    version: 0.6.0
  containerd:
    version: 1.3.7
```

Installed on CentOs 8.2
